### ISSUE TITLE
Support for database sequences

### ISSUE THREAD

**Issue by PeterJCLaw** [danpalmer/django-devdata#1]
It would be great if django-devdata provided support in some form for database sequences. (It would be great if _Django_ did too!)
A couple of ways I think this could work:
- a list of them configured in settings so that the export command knows which ones to pull from the database
- autodetection of them from the source database during export

Either way, it would be great if they were present after doing an import. I suspect we'd need to preserve the current value of the sequence too, where possible.

**Comment by PeterJCLaw** [comment]
@danpalmer just wondered if you had any thoughts on how to approach this? I'd be interested in picking this up at some point, but might be useful to have some pointers towards why this limitation exists/what's already been explored/what you think might be needed here.

**Comment by danpalmer** [comment]
@PeterJCLaw this was definitely skipped due to lack of immediate need (at the time) and the fact that they're not represented in Django's models.

As the models are devdata's source of truth there isn't a convenient equivalent to hang the sequences support off. However, because they're simpler we should be able to just always insert them all at the beginning.

Perhaps we could start with:
- Introducing a Sequence strategy class
   - Adding some initial utility implementations with extraction and/or hard-coded start/stop/current value/etc.
- Adding a sequence strategies setting, distinct from the model based strategies.
- Iterating through each during export
- Iterating through each during import and adding to the database before model strategies.

There shouldn't be any interdependencies I don't think so hopefully these should be much simpler than the model equivalents.

What do you think? It's been a while since I've looked at the codebase so I could be a little off on the pieces required.

**Comment by PeterJCLaw** [comment]
Having a look at this this evening and it looks like the current `Strategy` & `Exportable` classes are (as you say) based around the expectation that there's a model for everything. One option might be to have sequences handled by a different hierarchy of mixins which don't have that limitation (likely we could pull out some common logic though); not sure if that's what you had in mind.

Something else we'll need to think about is how to know which sequences to export. Obviously requiring users to list them manually would work, though doesn't feel ideal. However auto-detecting them would likely require a mechanism to filter out those which are attached to fields (and would thus be created by the schema import).

An idea therefore might be to allow devdata to run against an existing empty database so that users can do their own schema export/import if they want to (which would include sequences, at least on Postgres), sidestepping the need to support them directly. I realise that doesn't fully solve this issue though.

**Comment by PeterJCLaw** [comment]
@danpalmer I've ended up going in a slightly different direction here. In #12 I've introduced the idea of "extra" strategies which aren't tied to database models and then implemented sequence export/import within that framework. (In theory I think the Django migrations table export could also fit into that framework, though I've not explored that). Would be good to get your thoughts on that approach.
